services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - selenium
    ports:
      - "8000:8000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/health')"]
      interval: 10s
      timeout: 15s
      retries: 3
      
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:5000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - SERVER_URL=http://backend:8000
  
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    shm_size: 2g # To prevent browser crashes due to limited shared memory
    environment:
      - DEBUG=true
    ports:
      - "4444:4444" # Expose Selenium's WebDriver port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge