# Use an official Node.js runtime as a parent image
FROM node:20-slim

# Set the working directory
WORKDIR /app/frontend

# Copy the rest of the application code
COPY ./frontend /app/frontend

# Install dependencies
# RUN npm install

# CMD ["npm", "install", "bcrypt@^5.0.0"]

# Expose the port the app runs on
EXPOSE 5000

# Command to run the application
CMD ["npm", "run", "dev"]