# Use an official Node.js runtime as a parent image
FROM python:3.11-slim

# Set the working directory
WORKDIR /app/agent

RUN pip install --upgrade pip

# Copy requirements.txt and install Python dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY ./Agent_Outputs /app/agent/Agent_Outputs
COPY ./AI_Agents /app/agent/AI_Agents
COPY ./ML_model /app/agent/ML_model
COPY ./Final_products /app/agent/Final_products
COPY .env .
COPY emailservice.py .
COPY Machine_Customer_Endpoint.py .
COPY requirements.txt .
COPY genie-cart-firebase-service-account.json .

# Change ownership and set permissions for /app/agent
RUN chown -R root:root /app/agent && chmod -R 777 /app/agent

# Expose the port the app runs on
EXPOSE 8085

# Command to run the application
CMD ["python", "Agent_Endpoint.py"]