services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: machine_customer
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3305:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:5000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - SERVER_URL=http://backend:8000
      
  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: machine_customer
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge
