name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - "3306:3306"
        options: > 
          --health-cmd="mysqladmin ping --silent" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get install docker-compose

      - name: Build and start services
        run: |
          docker-compose up -d

      - name: Wait for services to be healthy
        run: |
          docker-compose run --rm frontend npm test

      - name: Cleanup
        run: |
          docker-compose down
